services:
    web:
        build: .
        ports:
            - "8000:8000"
        command: gunicorn lamps_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
        volumes:
            - .:/code